base/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, CustomLoginView, RegisterPage

from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', TaskDelete.as_view(), name='task-delete'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models. TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete'] 

base/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from .models import Task

# Create your views here.

class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('tasks')
    

class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)
    
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        else:
            return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user = self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__startswith=search_input)

        context['search_input'] = search_input
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('tasks')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('tasks')

base/templates/base/login.html
{% extends 'base/main.html' %}

{% block content %}

<div class="login_form_container">
    <a class="go_back" href="{% url 'tasks' %}"> Go back</a>

    <div class="login_form_wrapper">

        <h1>Login</h1>

        <form class="login_form" action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="login_submit_button" type="submit" value="Login"/>
        </form>

    </div>

    <p class="register_queston">Don't have an account? <a href="{% url 'register' %}">Register</a></p>

</div>

{% endblock %}

base/templates/base/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>To Do Items</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <link rel="stylesheet" href="{% static 'css/task_confirm_delete.css' %}">
    <link rel="stylesheet" href="{% static 'css/task_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/task_list.css' %}">
</head>
<body>
    <header>
        <h1>Todo App</h1>
        <nav>
            {% if request.user.is_authenticated %}
            <a class="login" href="{% url 'logout' %}"><button type="button">Logout</button></a>
            <div class="user_card">
                <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <circle cx="12" cy="9" r="3" stroke="#AAA" stroke-width="1.5"/>
                    <circle cx="12" cy="12" r="10" stroke="#AAA" stroke-width="1.5"/>
                    <path d="M17.9691 20C17.81 17.1085 16.9247 15 11.9999 15C7.07521 15 6.18991 17.1085 6.03076 20" stroke="#AAA" stroke-width="1.5" stroke-linecap="round"/>
                </svg>
                <p class="user">{{ request.user }}</p>
            </div>
            {% else %}
            <a class="logout" href="{% url 'login' %}"><button type="button">Login</button></a>
            <div class="user_card">
                <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <circle cx="12" cy="9" r="3" stroke="#AAA" stroke-width="1.5"/>
                    <circle cx="12" cy="12" r="10" stroke="#AAA" stroke-width="1.5"/>
                    <path d="M17.9691 20C17.81 17.1085 16.9247 15 11.9999 15C7.07521 15 6.18991 17.1085 6.03076 20" stroke="#AAA" stroke-width="1.5" stroke-linecap="round"/>
                </svg>
                <p class="user">Unknown</p>
            </div>
            {% endif %}
        </nav>
    </header>
    <aside></aside>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    
</body>
</html>

base/templates/base/register.html
{% extends 'base/main.html' %}

{% block content %}

<div class="register_form_container">
    <a class="go_back" href="{% url 'tasks' %}"> Go back</a>

    <div class="register_form_wrapper">
        <h1>Register</h1>
            
        <form class="register_form" action="" method="post">
            
            {% csrf_token %}
            {{ form.as_ul }}

            <input class="register_submit_button" type="submit" value="Register"/>
        </form>
    </div>

    <p class="login_question">Already have an account? <a href="{% url 'login' %}">Login</a></p>
</div>

{% endblock %}

base/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}

{% block content %}

<div class="delete_form">
    <a href="{% url 'tasks' %}">Go back</a>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this task?</p>
        <input type="submit" value="Delete"/>
    </form>
</div>

{% endblock %}

base/templates/base/task_form.html
{% extends 'base/main.html' %}

{% block content %}

<div class="new_task_container">
    <a href="{% url 'tasks' %}"> Go back</a>
    <div class="new_task_wrapper">

        <h1>Task Form</h1>
        <form class="new_task_form" action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="new_task_form_button" type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

base/templates/base/task_list.html
    {% extends 'base/main.html' %}

    {% block content %}

    <div class="task_list_form">
    
        <form class="search" method="get">
            <input class="search_input" type="text" name="search-area" value="{{ search_input }}" placeholder="Enter the task your looking for">
            <input class="submit_search" type="submit" value="Search">
        </form>

        <a class="add_task" href="{% url 'task-create' %}"><button type="button">Add Task</button></a>

        <div class="divider"></div>

        <table class="task_table">
            {% for task in tasks %}
            <tbody>
                <tr class="task">
                    {% if task.complete %}
                        <td class="task_column"><s>{{ task.title }}</s></td>
                    {% else %}
                        <td class="task_column">{{ task.title }}</td>
                    {% endif %}
                    <td class="edit_column"><a href="{% url 'task-update' task.id %}">Edit</a></td>
                    <td class="delete_column"><a href="{% url 'task-delete' task.id %}">Delete</a></td>
                </tr>
            </tbody>
            {% empty %}
            <h3>No items in list</h3>
            {% endfor %}
        </table>
    </div>

{% endblock %}
 